"""initial schema

Revision ID: 0ac3ffc1cd42
Revises: 
Create Date: 2026-04-09 21:24:03.536303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0ac3ffc1cd42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language_of_origin', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vector_dim', sa.Integer(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'label', name='uq_method_model_label')
    )
    op.create_table('taxonomy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corpus_level',
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.PrimaryKeyConstraint('corpus_id', 'height')
    )
    op.create_table('corpus_to_taxonomy',
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.id'], ),
    sa.PrimaryKeyConstraint('corpus_id', 'taxonomy_id')
    )
    op.create_table('corpus_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('translation_name', sa.Text(), nullable=True),
    sa.Column('translator', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('corpus_version_id', sa.Integer(), nullable=False),
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('reference_label', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('uncleaned_text', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('ancestor_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.ForeignKeyConstraint(['corpus_version_id'], ['corpus_version.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unit_corpus_height', 'unit', ['corpus_id', 'height'], unique=False)
    op.create_index('ix_unit_corpus_version', 'unit', ['corpus_version_id'], unique=False)
    op.create_index('ix_unit_parent', 'unit', ['parent_id'], unique=False)
    op.create_table('embedding',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'method_id', name='uq_embedding_unit_method')
    )
    op.create_index('ix_embedding_method', 'embedding', ['method_id'], unique=False)
    op.create_index('ix_embedding_unit', 'embedding', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embedding_unit', table_name='embedding')
    op.drop_index('ix_embedding_method', table_name='embedding')
    op.drop_table('embedding')
    op.drop_index('ix_unit_parent', table_name='unit')
    op.drop_index('ix_unit_corpus_version', table_name='unit')
    op.drop_index('ix_unit_corpus_height', table_name='unit')
    op.drop_table('unit')
    op.drop_table('corpus_version')
    op.drop_table('corpus_to_taxonomy')
    op.drop_table('corpus_level')
    op.drop_table('taxonomy')
    op.drop_table('method')
    op.drop_table('corpus')
    # ### end Alembic commands ###
