[project]
name = "ftf-backend"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "alembic",
    "fastapi",
    "pgvector",
    "psycopg[binary]",
    "pydantic",
    "python-dotenv",
    "sentence-transformers",
    "sqlalchemy",
    "uvicorn[standard]",
]

[tool.uv]
package = false
